#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM docker.io/library/golang:alpine AS build

COPY . /home/root

WORKDIR /home/root
RUN go build -o main .

FROM alpine AS run

RUN adduser -S fritz -G root
USER fritz

COPY --from=build --chown=fritz:root /home/root/main /home/fritz/main

EXPOSE 9090
ENTRYPOINT ["/home/fritz/main"]
